name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: noker81/noker81.github.io:latest

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: your-remote-server
        username: your-ssh-username
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          docker pull noker81/noker81.github.io:latest
          docker stop your-container-name || true
          docker rm your-container-name || true
          docker run -d --name your-container-name -p 80:80 noker81/noker81.github.io:latest
